language: ruby
env:
  global:
  - secure: "ULerMTYVWWq35zdVWObKmhJHCtre23CBTDLuB3GPGdxleyoZ2zmCngy08nBvnZoiFLcXaa5AYAGHtv3Wi7GAWfXgirHZzsbwalcA00l8wWgir9dwGh6iscapDKEBSLpgJ3X7py8U6SRo3wCJHNjti/+BiBgfho+ry1M/8atDrxQ="
rvm:
  - 2.4.0
  - 2.3.3
  - 2.2
  - 2.1.2
  - 2.0.0
  - 1.9.3
  - jruby-19mode
  - jruby-head
  - ruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
before_install:
  - gem update --system
  - gem update bundler
