---
name: bing_translator tests
on:
  push:
  pull_request:
  schedule:
    - cron: 0 12 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.4', '2.5', '2.6', '2.7' ]
    name: Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Run tests
        env:
          COGNITIVE_SUBSCRIPTION_KEY: ${{ secrets.COGNITIVE_SUBSCRIPTION_KEY }}
        run: |
          gem install bundler
          bundle install
          rspec --color --tty
